// Copyright (c) Alexander Polenov
export const LINE_TYPES = Object.freeze({
    drDoor: 1,
    w1DoorStayOpen: 2,
    w1DoorClose: 3,
    w1Door: 4,
    w1FloorToLowestAdjacentCeiling: 5,
    w1StartCrusherFastDamage: 6,
    s1BuildStairs8Up: 7,
    w1BuildStairs8Up: 8,
    s1FloorDonut: 9,
    w1LiftAlsoMonsters: 10,
    s1ExitNormal: 11,
    w1LightToHighestAdjacentLevel: 12,
    w1LightTo255: 13,
    s1FloorUp32ChangeTexture: 14,
    s1FloorUp24ChangeTexture: 15,
    w1DoorCloseAndOpen: 16,
    w1LightBlink1Sec: 17,
    s1FloorToHigherAdjacentFloor: 18,
    w1FloorToHighestAdjacentFloor: 19,
    s1FloorToHigherFloorChangeTexture: 20,
    s1Lift: 21,
    w1FloorToHigherFloorChangeTexture: 22,
    s1FloorToLowestAdjacentFloor: 23,
    g1FloorToLowestAdjacentCeiling: 24,
    w1StartCrusherSlowDamage: 25,
    drDoorBlueKey: 26,
    drDoorYellowKey: 27,
    drDoorRedKey: 28,
    s1Door: 29,
    w1FloorUpShortestLowerTexture: 30,
    d1DoorStayOpen: 31,
    d1DoorBlueKey: 32,
    d1DoorRedKey: 33,
    d1DoorYellowKey: 34,
    w1LightTo35: 35,
    w1FloorTo8AboveHighestAdjacentFloorFast: 36,
    w1FloorToLowestAdjacentFloorChangeTextureAndType: 37,
    w1FloorToLowestAdjacentFloor: 38,
    w1Teleport: 39,
    w1CeilingToHighestCeiling: 40,
    s1CeilingToFloor: 41,
    srDoorClose: 42,
    srCeilingToFloor: 43,
    w1CeilingTo8AboveFloor: 44,
    srFloorToHighestAdjacentFloor: 45,
    grDoorAlsoMonsters: 46,
    g1FloorToHigherFloorChangeTexture: 47,
    scrollingWallLeft: 48,
    s1StartCrusherSlowDamage: 49,
    s1DoorClose: 50,
    s1ExitSecret: 51,
    w1ExitNormal: 52,
    w1StartMovingFloor: 53,
    w1StopMovingFloor: 54,
    s1FloorTo8BelowLowestAdjacentCeilingAndCrush: 55,
    w1FloorTo8BelowLowestAdjacentCeilingAndCrush: 56,
    w1StopCrusher: 57,
    w1FloorUp24: 58,
    w1FloorUp24ChangeTextureAndType: 59,
    srFloorToLowestAdjacentFloor: 60,
    srDoorStayOpen: 61,
    srLift: 62,
    srDoor: 63,
    srFloorToLowestAdjacentCeiling: 64,
    srFloorTo8BelowLowestAdjacentCeilingAndCrush: 65,
    srFloorUp24ChangeTexture: 66,
    srFloorUp32ChangeTexture: 67,
    srFloorToHigherFloorChangeTexture: 68,
    srFloorToHigherAdjacentFloor: 69,
    srFloorTo8AboveHigherAdjacentFloorFast: 70,
    s1FloorTo8AboveHigherAdjacentFloorFast: 71,
    wrCeilingTo8AboveFloor: 72,
    wrStartCrusherSlowDamage: 73,
    wrStopCrusher: 74,
    wrDoorClose: 75,
    wrDoorCloseAndOpen: 76,
    wrStartCrusherFastDamage: 77,
    wrLightTo35: 79,
    wrLightToHighestAdjacentLevel: 80,
    wrLightTo255: 81,
    wrFloorToLowestAdjacentFloor: 82,
    wrFloorToHighestAdjacentFloor: 83,
    wrFloorToLowestAdjacentFloorChangeTextureAndType: 84,
    wrDoorStayOpen: 86,
    wrStartMovingFloor: 87,
    wrLiftAlsoMonsters: 88,
    wrStopMovingFloor: 89,
    wrDoor: 90,
    wrFloorToLowestAdjacentCeiling: 91,
    wrFloorUp24: 92,
    wrFloorUp24ChangeTextureAndType: 93,
    wrFloorTo8BelowLowestAdjacentCeilingAndCrush: 94,
    wrFloorToHigherFloorChangeTexture: 95,
    wrFloorUpShortestLowerTexture: 96,
    wrTeleport: 97,
    wrFloorTo8AboveHighestAdjacentFloorFast: 98,
    srDoorBlueKeyFast: 99,
    w1BuildStairs16AndCrush: 100,
    s1FloorToLowestAdjacentCeiling: 101,
    s1FloorToHighestAdjacentFloor: 102,
    s1DoorStayOpen: 103,
    w1LightToLowestAdjacentLevel: 104,
    wrDoorFast: 105,
    wrDoorStayOpenFast: 106,
    wrDoorCloseFast: 107,
    w1DoorFast: 108,
    w1DoorStayOpenFast: 109,
    w1DoorCloseFast: 110,
    s1DoorFast: 111,
    s1DoorStayOpenFast: 112,
    s1DoorCloseFast: 113,
    srDoorFast: 114,
    srDoorStayOpenFast: 115,
    srDoorCloseFast: 116,
    drDoorFast: 117,
    d1DoorFast: 118,
    w1FloorToHigherAdjacentFloor: 119,
    wrLiftFast: 120,
    w1LiftFast: 121,
    s1LiftFast: 122,
    srLiftFast: 123,
    w1ExitSecret: 124,
    w1TeleportMonstersOnly: 125,
    wrTeleportMonstersOnly: 126,
    s1BuildStairs16Crush: 127,
    wrFloorToHigherAdjacentFloor: 128,
    wrFloorToHigherFloorFast: 129,
    w1FloorToHigherFloorFast: 130,
    s1FloorToHigherFloorFast: 131,
    srFloorToHigherFloorFast: 132,
    s1DoorBlueKeyFast: 133,
    srDoorRedKeyFast: 134,
    s1DoorRedKeyFast: 135,
    srDoorYellowKeyFast: 136,
    s1DoorYellowKeyFast: 137,
    srLightTo255: 138,
    srLightTo35: 139,
    s1FloorUp512: 140,
    w1StartCrusherSilent: 141
});

export const SECTOR_TYPES = Object.freeze({
    randomBlink: 1,
    blink2Hz: 2,
    blink1Hz: 3,
    damage20Blink2Hz: 4,
    damage10: 5,
    damage5: 7,
    lightGlow: 8,
    secret: 9,
    doorCloseStayAfter30Sec: 10,
    damage20EndLevel: 11,
    blink1HzSync: 12,
    blink2HzSync: 13,
    doorOpenClose5min: 14,
    damage20: 16,
    flicker: 17,
});

export const THING_TYPES = Object.freeze({
    player1Start: 1,
    player2Start: 2,
    player3Start: 3,
    player4Start: 4,
    deathmatchStart: 11,
    teleportDestination: 14,

    zombieman: 3004,
    shotgunGuy: 9,
    heavyWeaponDude: 65,
    imp: 3001,
    demon: 3002,
    spectre: 58,
    lostSoul: 3006,
    cacodemon: 3005,
    painElemental: 71,
    revenant: 66,
    mancubus: 67,
    arachnotron: 68,
    hellKnight: 69,
    baronOfHell: 3003,
    archvile: 64,
    spiderMastermind: 7,
    cyberdemon: 16,
    wolfensteinSS: 84,
    commanderKeen: 72,
    bossBrain: 88,
    bossShooter: 89,
    spawnSpot: 87,

    shotgun: 2001,
    superShotgun: 82,
    chaingun: 2002,
    rocketLauncher: 2003,
    plasmaRifle: 2004,
    chainsaw: 2005,
    bfg9000: 2006,

    clip: 2007,
    ammoBox: 2048,
    shells: 2008,
    shellBox: 2049,
    rocket: 2010,
    rocketBox: 2046,
    cell: 2047,
    cellPack: 17,
    backpack: 8,

    stimpack: 2011,
    medikit: 2012,
    healthBonus: 2014,
    armorBonus: 2015,
    greenArmor: 2018,
    blueArmor: 2019,
    soulsphere: 2013,
    megasphere: 83,

    invulnerability: 2022,
    berserk: 2023,
    invisibility: 2024,
    radiationSuit: 2025,
    computerMap: 2026,
    lightAmpVisor: 2045,

    blueKeycard: 5,
    yellowKeycard: 6,
    redKeycard: 13,
    blueSkull: 40,
    yellowSkull: 39,
    redSkull: 38,

    // Decorations from now on
    barrel: 2035,
    burningBarrel: 70,             // Only Doom II.

    tallGreenPillar: 30,
    shortGreenPillar: 31,
    tallRedPillar: 32,
    shortRedPillar: 33,
    shortGreenPillarWithHeart: 36,
    shortRedPillarWithSkull: 37,
    tallTechnoPillar: 48,

    floorLamp: 2028,
    tallTechnoLamp: 85,            // Only Doom II.
    shortTechnoLamp: 86,           // Only Doom II.
    candelabra: 35,

    tallBlueFirestick: 44,
    tallGreenFirestick: 45,
    tallRedFirestick: 46,
    shortBlueFirestick: 55,
    shortGreenFirestick: 56,
    shortRedFirestick: 57,

    burntTree: 43,
    largeBrownTree: 54,
    stalagmite: 47,
    evilEye: 41,
    floatingSkull: 42,

    impaledHuman: 25,
    twitchingImpaledHuman: 26,
    skullOnPole: 27,
    fiveSkullShishKebab: 28,
    pileOfSkullsAndCandles: 29,

    hangingVictimTwitching: 49,
    hangingVictimArmsOut: 50,
    hangingVictimOneLegged: 51,
    hangingPairOfLegs: 52,
    hangingLeg: 53,
    hangingVictimTwitchingPassable: 63,
    hangingVictimArmsOutPassable: 59,
    hangingVictimOneLeggedPassable: 61,
    hangingPairOfLegsPassable: 60,
    hangingLegPassable: 62,

    hangingVictimGutsRemoved: 73,             // Only Doom II.
    hangingVictimGutsAndBrainRemoved: 74,     // Only Doom II.
    hangingTorsoLookingDown: 75,              // Only Doom II.
    hangingTorsoOpenSkull: 76,                // Only Doom II.
    hangingTorsoLookingUp: 77,                // Only Doom II.
    hangingTorsoBrainRemoved: 78,             // Only Doom II.

    // Flat scenery, none of it blocks movement.
    candle: 34,
    deadPlayer: 15,
    deadZombieman: 18,
    deadShotgunGuy: 19,
    deadImp: 20,
    deadDemon: 21,
    deadCacodemon: 22,
    bloodyMess: 10,
    bloodyMess2: 12,
    poolOfBloodAndFlesh: 24,
    poolOfBlood: 79,                         // Only Doom II.
    poolOfBlood2: 80,                        // Only Doom II.
    poolOfBrains: 81,                        // Only Doom II.
});
